### ISSUE TITLE
duration update to 0.1.3 breaks your tests

### ISSUE THREAD

**Issue by hannesm** [jeffa5/owork#14]
see https://ci.ocaml.org/log/saved/docker-run-761a57d852cb4c5a7099668a610270af/8ee023fcd732a74b85681f406a3ab0d35a174a51 -- the most recent duration release does not emit a trailing space in `Duration.pp` -- but your expect-tests expect that space. would be good to update your tests! :)

**Comment by jeffa5** [comment]
Thanks!
